/** Flat page routes — no /otc/, /ptp/, /inventory/ prefixes */
export const ROUTES = {
  dashboard: "/",
  salesOrders: "/sales-orders",
  salesOrdersNew: "/sales-orders/new",
  approvals: "/approvals",
  pick: "/pick",
  pack: "/pack",
  ship: "/ship",
  invoices: "/invoices",
  customerPayments: "/customer-payments",
  arAging: "/ar-aging",
  arKpi: "/ar-kpi",
  purchaseOrders: "/purchase-orders",
  purchaseOrdersNew: "/purchase-orders/new",
  receive: "/receive",
  vendors: "/vendors",
  vendorsNew: "/vendors/new",
  bills: "/bills",
  billsNew: "/bills/new",
  billPayments: "/bill-payments",
  billApprovals: "/bill-approvals",
  apAging: "/ap-aging",
  apKpi: "/ap-kpi",
  items: "/items",
  itemsNew: (type?: string) => (type ? `/items/new?type=${type}` : "/items/new"),
  warehouses: "/warehouses",
  adjust: "/adjust",
  transfer: "/transfer",
  itemStrategy: "/item-strategy",
  reportingStrategy: "/reporting-strategy",
  physicalWorksheet: "/physical-worksheet",
  inventoryKpi: "/inventory-kpi",
  salesByItems: "/sales-by-items",
  purchaseByItems: "/purchase-by-items",
  analyzeInventory: "/analyze-inventory",
} as const;
